export enum ResourceKeys {
  CATEGORIA = 'categorias',
  ARMAZEM = 'armazens',
  CHARTS = 'charts',
  EMPRESTIMO = 'emprestimos',
  ESTOQUE = 'estoques',
  FORNECEDORA = 'fornecedoras',
  MOVIMENTO_ESTOQUE = 'movimento-estoque',
  ORGANIZATION = 'organizations',
  PARCEIRO = 'parceiros',
  REQUISICAO_ESTOQUE = 'requisicoes-estoque',
  REQUISITANTE = 'requisitantes',
  SETOR = 'setores',
  TRANSPORTADORA = 'transportadoras',
  NFE_COMPRA = 'nfes-compra',
  USER = 'users',
  VINCULO = 'vinculos',
  INSUMO = 'insumos',
}
